config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'staff', to: 'pages#staff'
  get 'events', to: 'pages#events'
  get 'videos', to: 'pages#videos'
  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
  def home
  end
  
  def about
  end
  
  def staff
  end
  
  def events
  end
  
  def videos
  end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <h3 class="text-center">Contact Us</h3>
    <div class="col-md-8 col-md-offset-2">
      <div class="well">
        <%= form_for "/contacts" do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :message %>
            <%= f.text_area :message, class: 'form-control' %>
          </div>
          <%= f.submit 'Submit', class: 'btn btn-default' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evenmatchup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    
  </head>
  
  <header>
    <section id = "custom-navbar">
       <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            
            <%= link_to "/", class: "navbar-brand" do %>
              EvenMatchupGaming
            <% end %>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to "Events", events_path %></li>
              <li><%= link_to "Players", staff_path %></li>
              <li><%= link_to "Videos", videos_path %></li>
              <li><%= link_to "Let's talk", new_contact_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </nav>
    </section>
  </header>
  

 <body>
      
     <%= yield %>
    
 </body>
    
    <!-- FOOTER -->
 <footer>
    <section id = "custom-navbar">
      <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          
          <%= link_to "/", class: "navbar-brand" do %>
            EvenMatchupGaming
          <% end %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Let's talk", new_contact_path %></li>
            <li><%= link_to "Events", events_path %></li>
            <li><%= link_to "Players", events_path %></li>
          </ul>
          
          <a href="https://www.facebook.com/elchelevi" class="fa fa-facebook"></a>
          <a href="https://twitter.com/n0ned" class="fa fa-twitter"></a>
          <a href="https://twitch.tv/n0ne13" class="fa fa-twitch"></a>
          
        </div><!--/.nav-collapse -->
      </div>
    </nav>
  </section>  
 </footer>
    
    
 
  
</html>

app/views/pages/about.html.erb
<div class = "container-fluid">

  <hr class="featurette-divider">

  <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">We offer premier eSports competition</h2>
        <p class="lead">EMG hosts Canada's largest and most prestigious events for fighting games. We create and broadcast memorable events that bring together eSports supporters from across the world.</p>
      </div>
      <div class="col-md-5">
        <img class="featurette-image img-responsive center-block" src="http://i.imgur.com/GTLeIc2.jpg" alt="Generic placeholder image">
      </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7 col-md-push-5">
      <h2 class="featurette-heading">Excellent community engagement</h2>
      <p class="lead">Our presence is built through our community. As a player led organization, our goal is to always elevate the fan experience.</p>
    </div>
    <div class="col-md-5 col-md-pull-7">
      <img class="featurette-image img-responsive center-block" src="http://i.imgur.com/YRvHd9Y.jpg" alt="Generic placeholder image">
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading">Diverse competitive events</span></h2>
      <p class="lead">We understand how to create and organize events of varying scales. Our most celebrated events include the international major “Get On My Level”, regional competition “Revenge of the 6ix”,  and weekly series “Smash On Tap”.</p>
    </div>
    <div class="col-md-5">
      <img class="featurette-image img-responsive center-block" src="http://i.imgur.com/9dKLfoD.jpg" alt="Generic placeholder image">
    </div>
  </div>

  <hr class="featurette-divider">
  
</div>

app/views/pages/events.html.erb
<div class = "container">

<!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <image class="first-slide" src="http://i.imgur.com/g43yHLL.jpg" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <p><a class="btn btn-lg btn-primary" href="https://smash.gg/tournament/get-on-my-level-2017/details" role="button">Sign up today</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="http://i.imgur.com/bfY8Gxa.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <p><a class="btn btn-lg btn-primary" href="https://smash.gg/tournament/revenge-of-the-6ix-episode-ii" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="http://i.imgur.com/CvqTBoL.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <p><a class="btn btn-lg btn-primary" href="#" role="button">View Group</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->
    
</div>

<section id = "events">
  <div class = "container-fluid">
    <div class = "row">
      
      <div class = "col-lg-12 col-sm-12">
        <div class = "well">
           <iframe width="560" height="315" src="https://www.youtube.com/embed/jNnL_av427E" frameborder="0" allowfullscreen></iframe>
           <h3>Get On My Level</h3>
           <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, ab, eos nam error eligendi labore excepturi suscipit harum cupiditate dolores animi amet earum magnam nulla consequuntur quibusdam minus esse nobis?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio, ipsam voluptatum voluptate facilis nulla dolor consectetur. Nisi, amet repudiandae illum quaerat vitae consectetur animi. Commodi, repellendus sequi eligendi accusantium voluptatum.</p>
        </div>
      </div>
      
    </div>
    
    <div class = "row">
      
      <div class = "col-lg-6 col-sm-12">
        <div class = "well">
           <iframe width="560" height="315" src="https://www.youtube.com/embed/oitFJ1CePIg" frameborder="0" allowfullscreen></iframe>
           <h3>Revenge of the 6ix</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, ab, eos nam error eligendi labore excepturi suscipit harum cupiditate dolores animi amet earum magnam nulla consequuntur quibusdam minus esse nobis?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio, ipsam voluptatum voluptate facilis nulla dolor consectetur. Nisi, amet repudiandae illum quaerat vitae consectetur animi. Commodi, repellendus sequi eligendi accusantium voluptatum.</p>
        </div>
      </div>
      
      <div class = "col-lg-6 col-sm-12">
        <div class = "well">
           <iframe width="560" height="315" src="https://www.youtube.com/embed/iEVHOn5iVSQ" frameborder="0" allowfullscreen></iframe>
           <h3>Smash on Tap</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, ab, eos nam error eligendi labore excepturi suscipit harum cupiditate dolores animi amet earum magnam nulla consequuntur quibusdam minus esse nobis?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio, ipsam voluptatum voluptate facilis nulla dolor consectetur. Nisi, amet repudiandae illum quaerat vitae consectetur animi. Commodi, repellendus sequi eligendi accusantium voluptatum.</p>
        </div>
      </div>
      
    </div>
    
  </div>
</section>

app/views/pages/home.html.erb
<div class = "title-page">
  <div class = jumbotron>
    <h1>Big Placeholder Logo</h1>
    <br>
    <h2>Canadian eSports team dedicated to building communities</h3>
    <p><a class="btn btn-default" href="/about" role="button">Learn More &raquo;</a></p>
  </div>
</div>
  
  
</div>


<div class = "container-fluid">

    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class = "well">
    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <img class="img-circle" src="http://i.imgur.com/WutAwvW.jpg" alt="Generic placeholder image" width="140" height="140">
          <h2>Our Team</h2>
          <p>Our goal is to promote Canadian eSports talent to fans all around the world. Look out for our sponsored players in upcoming major tournaments.</p>
          <p><a class="btn btn-default" href="/staff" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="http://i.imgur.com/8ZbT6Ad.jpg" alt="Generic placeholder image" width="140" height="140">
          <h2>Video Content</h2>
          <p>We provide state of the art streams for all of our hosted events as well as engaging highlight reels. Tune in to watch top Canadian competitive play, inciteful commentary and more information on upcoming events!</p>
          <p><a class="btn btn-default" href="/videos" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="http://i.imgur.com/ik7zsgU.jpg" alt="Generic placeholder image" width="140" height="140">
          <h2>Events</h2>
          <p>We run eSports tournaments out of Canada on a weekly, monthly and yearly basis. Come join us to connect with the Canadian gaming community.</p>
          <p><a class="btn btn-default" href="/events" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->
      
  </div>
</div>
<!-- Social media links --> 

<section id = "social-media">
  
   <hr class="featurette-divider">
  
    <h1>Stay connected with EvenMatchupGaming</h1>
    <h3>Follow us for our upcoming events and high quality content</h3>
  
    <div class = "row">
      <div class = "container">
      <div class = "col-md-6 col-lg-3 col-sm-6">
        <a href="http://facebook.com/evenmatchupgaming" class="fa fa-facebook">
          <h3>/EvenMatchupGaming</h3>
          <p>Latest events</p>
        </a>
    
      </div>
      <div class = "col-md-6 col-lg-3 col-sm-6">
        <a href="http://twitter.com/evenmatchup" class="fa fa-twitter">
          <h3>/EvenMatchup</h3>
          <p>Latest News</p>
        </a>
        
      </div>
      <div class = "col-md-6 col-lg-3 col-sm-6">
        <a href="http://youtube.com/evenmatchupgaming" class="fa fa-youtube">
          <h3>/EvenMatchupGaming</h3>
          <p>Newest videos</p>
        </a>
        
      </div>
      <div class = "col-md-6 col-lg-3 col-sm-6">
        <a href="http://twitch.tv/evenmatchupgaming" class="fa fa-twitch">
          <h3>/EvenMatchupGaming</h3>
          <p>Live Streams</p>
        </a>
        
      </div>
    </div>
  </div>
  
</div>
     
</section> 
     
  

app/views/pages/staff.html.erb
<div class = "container-fluid">
  <div class = "row">
    <div class = "col-lg-12 col-md-12">
      <div class = "team-member">
        <div class = "team-profile-photo">
          <img src="http://i.imgur.com/CfdsUja.jpg" alt="Generic placeholder image">
        </div>
        <div class = "player-description">
          <h2>Vikram <span class = "player-tag">'Nightmare'</span> Bassi</h2>
          <div id = "player-social-media">
            <a href="https://www.facebook.com/profile.php?id=100011763427906&fref=ts" class="fa fa-facebook"></a>
            <a href="https://twitter.com/Nightmare6God" class="fa fa-twitter"></a>
            <a href="https://www.twitch.tv/nightmare6god" class="fa fa-twitch"></a>
          </div>
          <br>
          <br>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio, deserunt, repudiandae, nemo, laudantium perferendis necessitatibus cupiditate harum numquam molestias iusto atque alias ipsam iste rem eaque quaerat quae corrupti reiciendis!Lorem ipsum dolor sit amet, consectetur adipisicing elit. In, rerum, molestiae ea voluptatibus est corrupti officiis dolorum deserunt. Deleniti, optio magni odit minus necessitatibus porro ex maxime expedita vel consectetur.</p>
        </div>
      </div>
    </div>
  </div>
  
  <div class = "row">
    <div class = "col-lg-12 col-md-12">
      <div class = "team-member">
        <div class = "team-profile-photo">
          <img src="http://i.imgur.com/ucD6NMW.jpg" alt="Generic placeholder image">
        </div>
        <div class = "player-description">
          <h2>Edgard <span class = "player-tag">'n0ne'</span> Sheleby</h2>
          <div id = "player-social-media">
            <a href="https://www.facebook.com/elchelevi" class="fa fa-facebook"></a>
            <a href="https://twitter.com/n0ned" class="fa fa-twitter"></a>
            <a href="https://twitch.tv/n0ne13" class="fa fa-twitch"></a>
          </div>
          <br>
          <br>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, sequi voluptatum velit placeat laborum accusamus necessitatibus neque delectus cum aperiam. Reprehenderit, quas, sint magnam rem architecto dignissimos aliquid sed asperiores!Lorem ipsum dolor sit amet, consectetur adipisicing elit. In, rerum, molestiae ea voluptatibus est corrupti officiis dolorum deserunt. Deleniti, optio magni odit minus necessitatibus porro ex maxime expedita vel consectetur.</p>
        </div>
      
      </div>
    </div>
  </div>
  
  <div class = "row">
    <div class = "col-lg-12 col-md-12">
      <div class = "team-member">
        <div class = "team-profile-photo">
          <img src="http://i.imgur.com/m5FYLCB.jpg" alt="Generic placeholder image">
        </div>
        <div class = "player-description">
          <h2>Aaron <span class = "player-tag">'Blacktwins'</span> Grandison-Vargas </h2>
          <div id = "player-social-media">
            <a href="https://www.facebook.com/aaron.grandisonvargas" class="fa fa-facebook"></a>
            <a href="https://twitter.com/blacktwins" class="fa fa-twitter"></a>
            <a href="https://twitch.tv/n0ne13" class="fa fa-twitch"></a>
          </div>
          <br>
          <br>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum, debitis, placeat aliquid quae ducimus corporis optio voluptatum magnam consectetur necessitatibus nemo ipsam voluptatem quidem eaque culpa fugit doloremque omnis quas.Lorem ipsum dolor sit amet, consectetur adipisicing elit. In, rerum, molestiae ea voluptatibus est corrupti officiis dolorum deserunt. Deleniti, optio magni odit minus necessitatibus porro ex maxime expedita vel consectetur.</p>
        </div>
      
      </div>
    </div>
  </div>
  
</div>

app/views/pages/videos.html.erb
<section id = "videos">
  <div class = "container-fluid">
    <div class = "row">
      
      <div class = "col-lg-6 col-md-6 col-sm-12">
        <div class = "well">
           <iframe width="560" height="315" src="https://www.youtube.com/embed/mBAZRqgY1PY" frameborder="0" allowfullscreen></iframe>
           <h3>Top plays of 2016 Melee</h3>
           <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, ab, eos nam error eligendi labore excepturi suscipit harum cupiditate dolores animi amet earum magnam nulla consequuntur quibusdam minus esse nobis?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio, ipsam voluptatum voluptate facilis nulla dolor consectetur. Nisi, amet repudiandae illum quaerat vitae consectetur animi. Commodi, repellendus sequi eligendi accusantium voluptatum.</p>
        </div>
      </div>
      
      <div class = "col-lg-6 col-md-6 col-sm-12">
        <div class = "well">
           <iframe width="560" height="315" src="https://www.youtube.com/embed/FU27bEz1R1k" frameborder="0" allowfullscreen></iframe>
           <h3>Top plays of 2016 WiiU</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, ab, eos nam error eligendi labore excepturi suscipit harum cupiditate dolores animi amet earum magnam nulla consequuntur quibusdam minus esse nobis?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio, ipsam voluptatum voluptate facilis nulla dolor consectetur. Nisi, amet repudiandae illum quaerat vitae consectetur animi. Commodi, repellendus sequi eligendi accusantium voluptatum.</p>
        </div>
      </div>
      
   
      
    </div>
    
    <div class = "row">
      
      <div class = "col-lg-6 col-sm-12">
        <div class = "well">
           <iframe width="560" height="315" src="https://www.youtube.com/embed/l98SRO_LOrI" frameborder="0" allowfullscreen></iframe>
           <h3>Canada Cup Top 8 Trailer</h3>
           <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, ab, eos nam error eligendi labore excepturi suscipit harum cupiditate dolores animi amet earum magnam nulla consequuntur quibusdam minus esse nobis?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio, ipsam voluptatum voluptate facilis nulla dolor consectetur. Nisi, amet repudiandae illum quaerat vitae consectetur animi. Commodi, repellendus sequi eligendi accusantium voluptatum.</p>
        </div>
      </div>
      
      <div class = "col-lg-6 col-sm-12">
        <div class = "well">
           <iframe width="560" height="315" src="https://www.youtube.com/embed/gDIyCp4tpMg" frameborder="0" allowfullscreen></iframe>
           <h3>Partners in Shine - Ice & Leffen</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, ab, eos nam error eligendi labore excepturi suscipit harum cupiditate dolores animi amet earum magnam nulla consequuntur quibusdam minus esse nobis?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio, ipsam voluptatum voluptate facilis nulla dolor consectetur. Nisi, amet repudiandae illum quaerat vitae consectetur animi. Commodi, repellendus sequi eligendi accusantium voluptatum.</p>
        </div>
      </div>
      
    </div>
    
    <div class = "row">
      
      <div class = "col-lg-6 col-md-6 col-sm-12">
        <div class = "well">
           <iframe width="560" height="315" src="https://www.youtube.com/embed/dqbMgZfqdsI" frameborder="0" allowfullscreen></iframe>
           <h3>Top plays of 2016 Smash64</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, ab, eos nam error eligendi labore excepturi suscipit harum cupiditate dolores animi amet earum magnam nulla consequuntur quibusdam minus esse nobis?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio, ipsam voluptatum voluptate facilis nulla dolor consectetur. Nisi, amet repudiandae illum quaerat vitae consectetur animi. Commodi, repellendus sequi eligendi accusantium voluptatum.</p>
        </div>
      </div>
      
      <div class = "col-lg-6 col-sm-12">
        <div class = "well">
           <iframe width="560" height="315" src="https://www.youtube.com/embed/5ENlmYY-rmQ" frameborder="0" allowfullscreen></iframe>
           <h3>Top n0ne plays 2016</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, ab, eos nam error eligendi labore excepturi suscipit harum cupiditate dolores animi amet earum magnam nulla consequuntur quibusdam minus esse nobis?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio, ipsam voluptatum voluptate facilis nulla dolor consectetur. Nisi, amet repudiandae illum quaerat vitae consectetur animi. Commodi, repellendus sequi eligendi accusantium voluptatum.</p>
        </div>
      </div>
      
    </div>
    
  </div>
</section>